name: Terraform Plan
trigger: none

pool: Ketan-Pool
variables:
  - group: todoapp-variable
stages:
  - stage: Terraformplan
    displayName: Terraform Plan
    jobs:
      - job: TerraformPlanJob
        displayName: Terraform Plan
        steps:
          
          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp-infra'
              backendServiceArm: 'ketan-svc-dec'
              backendAzureRmResourceGroupName: 'ketan-rg'
              backendAzureRmStorageAccountName: 'strgtfstateketan'
              backendAzureRmContainerName: 'tfstateketan'
              backendAzureRmKey: 'ketandevops.terraform.tfstate'
          

              
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp-infra'
              environmentServiceNameAzureRM: 'ketan-svc-dec'
          
