name : Terraform_Apply_Pipeline
trigger : none

pool: Ketan-Pool
  
#pool : 
#  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: DevopsTemplate
      type: git
      name: CloudDevops/DevopsTemplate


parameters:
- name: environment
  displayName: environment
  type: string
  default: "tst"
  values: ["prd","stg","tst"]


variables:
  - group: common-backend-info
  - group: todoapp-variable
  
stages:
  - stage: TerraformApply
    displayName: Terraform Apply

    jobs:
      - deployment: TerraformPlan
        displayName: Terraform Plan 
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - checkout: DevopsTemplate
              - template: steps/terraform/plan_new.yaml@DevopsTemplate
                parameters:
                  commandOptions: "-var-file=config.${{ parameters.environment }}.tfvars"
                  condition: succeeded()
                  working_directory: "$(System.DefaultWorkingDirectory)/InfraCode/todoapp-infra"
                  backend_service_connection: "$(backend_service_connection)"


      - job: ReviewAndValidatePlan
        dependsOn: TerraformPlan
        displayName: Review and Validate Plan
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 15
            inputs:
              instructions: 'Review the Plan. Reject if incorrect, Resume if correct. If in doubt, seek assistance.'
              onTimeout: 'reject'
              #notifyUsers: |
               # '[Cloud Platform]\Cloud Platform Lead Engineers'

      - deployment: TerraformApply
        dependsOn: ReviewAndValidatePlan
        displayName: Terraform Apply
        environment: ${{ parameters.environment }}_restricted
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: DevopsTemplate
              - checkout: self
              - template: steps/terraform/apply.yaml@DevopsTemplate
                # parameters:
                #   commandOptions: "-var-file=config.${{ parameters.environment }}.tfvars"
              #     condition: succeeded()
              #     working_directory: "$(System.DefaultWorkingDirectory)/InfraCode/todoapp-infra"
              #     backend_service_connection: "$(backend_service_connection)"
              # #- template: steps/terraform/apply.yaml@DevopsTemplate

